

server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: accounts
            uri: lb://accounts-service
            predicates:
              - Path=/accounts/**
          - id: clients
            uri: lb://clients-service
            predicates:
              - Path=/clients/**
  application:
    name: gateway-service


springdoc:
  cache:
    disabled: true
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
  api-docs:
    version: openapi_3_1
