spring:
  application:
    name: accounts-service
  data:
    mongodb:
      uri: mongodb://karina:123456@mongodb:27017/master_microservices?authSource=admin


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8762/eureka/
#  instance:
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#server:
#  port: 0